/**********************
 * BASE DE DATOS CINE *
 **********************/

-- Consulta 1
SELECT DISTINCT COD_PAIS FROM ACTOR ORDER BY COD_PAIS ASC;

-- Consulta 2
SELECT COD_PELI, TITULO FROM PELICULA WHERE ANYO < 1970 AND COD_LIB IS NULL ORDER BY TITULO;

-- Consulta 3
SELECT COD_ACT, NOMBRE FROM ACTOR WHERE NOMBRE LIKE '%John%';

-- Consulta 4
SELECT COD_PELI, TITULO FROM PELICULA WHERE ANYO BETWEEN 1980 AND 1989 AND DURACION > 120;

-- Consulta 5
SELECT COD_PELI, TITULO FROM PELICULA WHERE COD_LIB IS NOT NULL AND DIRECTOR LIKE '%Pakula%';

-- Consulta 6
SELECT COUNT(*) FROM PELICULA WHERE ANYO BETWEEN 1980 AND 1989 AND DURACION > 120;

-- Consulta 7
SELECT COUNT(DISTINCT COD_PELI) CUÁNTAS_PELIS FROM CLASIFICACION WHERE COD_GEN IN ('BB5','GG4','JH6');

-- Consulta 8
SELECT MIN(ANYO) AÑO FROM LIBRO_PELI;

-- Consulta 9
SELECT AVG(DURACION) DURACIÓN_MEDIA FROM PELICULA WHERE ANYO=1987;

-- Consulta 10
SELECT SUM(DURACION) DURAN_MIN FROM PELICULA WHERE DIRECTOR='Steven Spielberg';

-- Consulta 11
SELECT P.COD_PELI, P.TITULO FROM PELICULA P, ACTUA A, ACTOR AC
WHERE AC.COD_ACT=A.COD_ACT AND A.COD_PELI = P.COD_PELI AND P.DIRECTOR = AC.NOMBRE ORDER BY P.TITULO;

-- Consulta 12
SELECT P.COD_PELI, P.TITULO FROM PELICULA P, CLASIFICACION C, GENERO G
WHERE P.COD_PELI = C.COD_PELI AND C.COD_GEN = G.COD_GEN AND G.NOMBRE = 'Comedia' ORDER BY P.TITULO;

-- Consulta 13
SELECT P.COD_PELI, P.TITULO FROM PELICULA P, LIBRO_PELI L
WHERE P.COD_LIB = L.COD_LIB AND L.ANYO < 1950 ORDER BY P.TITULO;

-- Consulta 14
SELECT DISTINCT P.COD_PAIS, P.NOMBRE FROM PAIS P, ACTOR A, ACTUA AC, PELICULA PE, CLASIFICACION C, GENERO G
WHERE P.COD_PAIS = A.COD_PAIS AND A.COD_ACT = AC.COD_ACT AND AC.COD_PELI = PE.COD_PELI 
	AND PE.COD_PELI = C.COD_PELI AND C.COD_GEN = G.COD_GEN AND G.NOMBRE = 'Comedia' ORDER BY P.NOMBRE;

-- Consulta 15a
SELECT P.COD_PELI, P.TITULO FROM PELICULA P
WHERE DIRECTOR IN (
	SELECT NOMBRE FROM ACTOR WHERE COD_ACT IN (
		SELECT A.COD_ACT FROM ACTUA A WHERE A.COD_PELI = P.COD_PELI
	)
) ORDER BY P.TITULO;

-- Consulta 15b
SELECT P.COD_PELI, P.TITULO FROM PELICULA P
WHERE P.COD_PELI IN (
	SELECT COD_PELI FROM CLASIFICACION WHERE COD_GEN IN (
		SELECT COD_GEN FROM GENERO WHERE NOMBRE='Comedia'
	)
) ORDER BY P.TITULO;

-- Consulta 15c
SELECT P.COD_PELI, P.TITULO FROM PELICULA P
WHERE P.COD_LIB IN (
	SELECT COD_LIB FROM LIBRO_PELI WHERE ANYO < 1950
) ORDER BY P.TITULO;

-- Consulta 15d
SELECT P.COD_PAIS, P.NOMBRE FROM PAIS P WHERE P.COD_PAIS IN (
	SELECT COD_PAIS FROM ACTOR A WHERE A.COD_ACT IN (
		SELECT COD_ACT FROM ACTUA WHERE COD_PELI IN (
			SELECT COD_PELI FROM PELICULA WHERE COD_PELI IN (
				SELECT COD_PELI FROM CLASIFICACION WHERE COD_GEN IN (
					SELECT COD_GEN FROM GENERO WHERE NOMBRE = 'Comedia'
				)
			)
		)
	)
) ORDER BY P.NOMBRE;

-- Consulta 16
SELECT COD_ACT, NOMBRE FROM ACTOR WHERE FECHA_NAC < TO_DATE('1950-01-01', 'yyyy-MM-dd')
AND COD_ACT IN (
	SELECT COD_ACT FROM ACTUA WHERE PAPEL = 'Principal'
) ORDER BY NOMBRE;

-- Consulta 17
SELECT COD_LIB, TITULO, AUTOR FROM LIBRO_PELI WHERE COD_LIB IN (
	SELECT COD_LIB FROM PELICULA WHERE ANYO BETWEEN 1990 AND 1999
) ORDER BY TITULO;

-- Consulta 18
SELECT COD_LIB, TITULO, AUTOR FROM LIBRO_PELI WHERE COD_LIB NOT IN (
	SELECT COD_LIB FROM PELICULA WHERE COD_LIB IS NOT NULL
);

-- Consulta 19
SELECT NOMBRE FROM GENERO WHERE COD_GEN IN (
	SELECT COD_GEN FROM CLASIFICACION WHERE COD_PELI NOT IN (
		SELECT COD_PELI FROM ACTUA
	)
) ORDER BY NOMBRE;

-- Consulta 20
SELECT TITULO FROM LIBRO_PELI WHERE COD_LIB NOT IN (
	SELECT COD_LIB FROM PELICULA WHERE COD_LIB IS NOT NULL AND COD_PELI IN (
		SELECT COD_PELI FROM ACTUA WHERE COD_ACT IN (
			SELECT COD_ACT FROM ACTOR WHERE COD_PAIS = (
				SELECT COD_PAIS FROM PAIS WHERE NOMBRE='USA'
			)
		)
	) 
) AND COD_LIB IN (SELECT COD_LIB FROM PELICULA WHERE COD_LIB IS NOT NULL) 
ORDER BY TITULO;

-- Consulta 21
SELECT COUNT(P.COD_PELI) FROM PELICULA P WHERE P.COD_PELI IN (
	SELECT COD_PELI FROM CLASIFICACION WHERE COD_GEN IN (
		SELECT COD_GEN FROM GENERO WHERE NOMBRE = 'Comedia'
	)
) AND 1 = (SELECT COUNT(*) FROM ACTUA A WHERE A.COD_PELI = P.COD_PELI AND PAPEL='Secundario');

-- Consulta 22
SELECT MIN(ANYO) FROM PELICULA WHERE COD_PELI IN (
	SELECT COD_PELI FROM ACTUA WHERE COD_ACT IN (
		SELECT COD_ACT FROM ACTOR WHERE NOMBRE='Jude Law'
	) AND PAPEL = 'Principal'
);

-- Consulta 23
SELECT COD_ACT, NOMBRE FROM ACTOR WHERE FECHA_NAC = (SELECT MIN(FECHA_NAC) FROM ACTOR);

-- Consulta 24
SELECT COD_ACT, NOMBRE, FECHA_NAC FROM ACTOR WHERE FECHA_NAC = (
	SELECT MIN(FECHA_NAC) FROM ACTOR 
		WHERE FECHA_NAC BETWEEN TO_DATE('1940-01', 'yyyy-MM') AND TO_DATE('1940-12', 'yyyy-MM')
);

-- Consulta 25
SELECT NOMBRE FROM GENERO WHERE COD_GEN IN (
	SELECT COD_GEN FROM CLASIFICACION WHERE COD_PELI IN (
		SELECT COD_PELI FROM PELICULA WHERE DURACION = (
			SELECT MAX(DURACION) FROM PELICULA
		)
	)
) ORDER BY NOMBRE;

-- Consulta 26
SELECT COD_LIB, TITULO FROM LIBRO_PELI WHERE COD_LIB IN (
	SELECT COD_LIB FROM PELICULA WHERE COD_LIB IS NOT NULL AND COD_PELI IN (
		SELECT COD_PELI FROM ACTUA WHERE COD_ACT IN (
			SELECT COD_ACT FROM ACTOR WHERE COD_PAIS = (
				SELECT COD_PAIS FROM PAIS WHERE NOMBRE='España'
			)
		)
	)
) ORDER BY TITULO;

-- Consulta 27
SELECT TITULO FROM PELICULA P WHERE ANYO < 1950 
AND  1 < (
	SELECT COUNT(*) FROM CLASIFICACION C WHERE C.COD_PELI = P.COD_PELI 
);

-- Consulta 28
SELECT COUNT(*) FROM PELICULA P WHERE 4 > (
	SELECT COUNT(*) FROM ACTUA A WHERE A.COD_PELI = P.COD_PELI  
);

-- Consulta 29
SELECT DISTINCT P.DIRECTOR FROM PELICULA P WHERE 250 < (
	SELECT SUM(P2.DURACION) FROM PELICULA P2 WHERE P.DIRECTOR=P2.DIRECTOR
);

-- Consulta 30
SELECT DISTINCT EXTRACT(YEAR FROM A.FECHA_NAC) AÑO FROM ACTOR A WHERE 3 < (
	SELECT COUNT(*) FROM ACTOR A2 WHERE EXTRACT(YEAR FROM A2.FECHA_NAC) = EXTRACT(YEAR FROM A.FECHA_NAC)
) ORDER BY AÑO DESC;

-- Consulta 31
SELECT COD_ACT, NOMBRE FROM ACTOR WHERE COD_ACT IN (
	SELECT COD_ACT FROM ACTUA WHERE COD_PELI IN (
		SELECT COD_PELI FROM PELICULA WHERE COD_PELI IN (
			SELECT COD_PELI FROM CLASIFICACION WHERE COD_GEN='DD8'
		)
	)
) AND FECHA_NAC = (SELECT MAX(FECHA_NAC) FROM ACTOR WHERE COD_ACT IN (
	SELECT COD_ACT FROM ACTUA WHERE COD_PELI IN (
		SELECT COD_PELI FROM CLASIFICACION WHERE COD_GEN='DD8'
	)
));

-- Consulta 32
SELECT COD_PAIS, NOMBRE FROM PAIS P WHERE NOT EXISTS (
	SELECT * FROM ACTOR A WHERE P.COD_PAIS = A.COD_PAIS
	AND NOT A.FECHA_NAC BETWEEN TO_DATE('1900-01','yyyy-MM') AND TO_DATE('1999-12', 'yyyy-MM')
) AND P.COD_PAIS IN (SELECT COD_PAIS FROM ACTOR) ORDER BY NOMBRE;

-- Consulta 33
SELECT A.COD_ACT, A.NOMBRE FROM ACTOR A WHERE NOT EXISTS (
	SELECT * FROM ACTUA AC WHERE A.COD_ACT = AC.COD_ACT 
	AND PAPEL <> 'Secundario'
) AND A.COD_ACT IN (SELECT COD_ACT FROM ACTUA)
ORDER BY A.NOMBRE;

-- Consulta 34
SELECT A.COD_ACT, A.NOMBRE FROM ACTOR A WHERE NOT EXISTS (
	SELECT * FROM PELICULA P WHERE DIRECTOR='Guy Ritchie' AND
	P.COD_PELI NOT IN (
		SELECT AC.COD_PELI FROM ACTUA AC WHERE AC.COD_ACT=A.COD_ACT
	)
) AND EXISTS (SELECT * FROM PELICULA WHERE DIRECTOR = 'Guy Ritchie') -- Existe el director
  AND EXISTS (SELECT * FROM ACTUA AC WHERE A.COD_ACT =AC.COD_ACT);	 -- El actor ha actuado en alguna película

-- Consulta 35
SELECT A.COD_ACT, A.NOMBRE FROM ACTOR A WHERE NOT EXISTS (
	SELECT * FROM PELICULA P WHERE DIRECTOR='John Steel' AND
	P.COD_PELI NOT IN (
		SELECT AC.COD_PELI FROM ACTUA AC WHERE AC.COD_ACT=A.COD_ACT
	)
) AND EXISTS (SELECT * FROM PELICULA WHERE DIRECTOR = 'John Steel')
  AND EXISTS (SELECT * FROM ACTUA AC WHERE A.COD_ACT = AC.COD_ACT);
 
 -- Consulta 36
 SELECT P.COD_PELI, P.TITULO FROM PELICULA P WHERE P.DURACION < 100
 AND NOT EXISTS (
 	SELECT * FROM ACTOR A WHERE A.COD_ACT IN (
 		SELECT COD_ACT FROM ACTUA A WHERE A.COD_PELI = P.COD_PELI
 	) AND 1 < ( SELECT COUNT(DISTINCT COD_PAIS) FROM ACTOR ACT WHERE ACT.COD_ACT IN (
 					SELECT COD_ACT FROM ACTUA A WHERE A.COD_PELI = P.COD_PELI) 
 	)
 ) AND P.COD_PELI IN (SELECT COD_PELI FROM ACTUA) 
ORDER BY P.COD_PELI; 

-- Consulta 37
SELECT P.COD_PELI, P.TITULO, P.ANYO FROM PELICULA P WHERE NOT EXISTS (
	SELECT * FROM ACTOR A WHERE A.COD_ACT IN (SELECT COD_ACT FROM ACTUA ACT WHERE ACT.COD_PELI=P.COD_PELI)
	AND A.FECHA_NAC > TO_DATE('31/12/1942', 'dd/MM/yyyy') 
) AND EXISTS (SELECT * FROM ACTUA AC WHERE AC.COD_PELI=P.COD_PELI) -- Que haya actuado algún actor 
ORDER BY P.TITULO ASC;

-- Consulta 38 (REPASAR, NO ES EL MISMO OUTPUT QUE EL BOLETÍN)
SELECT PA.COD_PAIS, PA.NOMBRE FROM PAIS PA WHERE NOT EXISTS (
	SELECT * FROM ACTOR A WHERE PA.COD_PAIS=A.COD_PAIS 
	AND A.COD_ACT NOT IN (	
	-- Comprobar si NO ha actuado en alguna peli de más de 120min
		SELECT ACT.COD_ACT FROM ACTUA ACT WHERE ACT.COD_PELI IN (
			SELECT COD_PELI FROM PELICULA WHERE DURACION > 120
		)
	) AND PA.COD_PAIS IN (SELECT COD_PAIS FROM ACTOR) -- Que haya actores de ese país
) ORDER BY PA.NOMBRE;

-- Consulta 38
SELECT PA.COD_PAIS, PA.NOMBRE FROM PAIS PA WHERE NOT EXISTS (
    SELECT * FROM ACTOR A WHERE PA.COD_PAIS=A.COD_PAIS 
    AND NOT EXISTS (
        SELECT * FROM ACTUA ACT, PELICULA P WHERE ACT.COD_ACT = A.COD_ACT AND ACT.COD_PELI=P.COD_PELI AND DURACION > 120)
    ) AND PA.COD_PAIS IN (SELECT COD_PAIS FROM ACTOR) 
    -- Que haya actores de ese país
 ORDER BY PA.NOMBRE;

-- Consulta 39
SELECT L.COD_LIB, L.TITULO, COUNT(P.COD_PELI) CUÁNTAS FROM LIBRO_PELI L, PELICULA P
WHERE P.COD_PELI IN (SELECT P2.COD_PELI FROM PELICULA P2 WHERE P2.COD_LIB = L.COD_LIB)
GROUP BY L.COD_LIB, L.TITULO
HAVING 1 < (SELECT COUNT(*) FROM PELICULA P2 WHERE P2.COD_LIB = L.COD_LIB);

-- Consulta 40
SELECT G.COD_GEN, G.NOMBRE, COUNT(C.COD_GEN), ROUND(AVG(P.DURACION)) 
FROM GENERO G, CLASIFICACION C, PELICULA P
WHERE C.COD_GEN = G.COD_GEN AND C.COD_PELI = P.COD_PELI 
GROUP BY G.COD_GEN, G.NOMBRE
HAVING 5 < (SELECT COUNT(*) FROM CLASIFICACION C2 WHERE C2.COD_GEN = G.COD_GEN)
ORDER BY G.NOMBRE;

-- Consulta 41
SELECT P.COD_PELI, P.TITULO, COUNT(C.COD_GEN) FROM PELICULA P, CLASIFICACION C
WHERE P.COD_PELI = C.COD_PELI
GROUP BY P.COD_PELI, P.TITULO
	-- No puede haber un atributo en HAVING que no está en GROUP BY
	HAVING 2000 < (SELECT P2.ANYO FROM PELICULA P2 WHERE P2.COD_PELI=P.COD_PELI)
ORDER BY P.TITULO;

-- Consulta 42
SELECT P.DIRECTOR FROM PELICULA P
WHERE P.DIRECTOR LIKE '%George%'
GROUP BY P.DIRECTOR
HAVING 2 = (SELECT COUNT(*) FROM PELICULA P2 WHERE P.DIRECTOR = P2.DIRECTOR);

-- Consulta 43
SELECT P.COD_PELI, P.TITULO, COUNT(A.COD_ACT) NUM_ACTORES
FROM PELICULA P, ACTUA A
WHERE A.COD_PELI = P.COD_PELI
GROUP BY P.COD_PELI, P.TITULO
HAVING 1 = (SELECT COUNT(*) FROM CLASIFICACION C WHERE C.COD_PELI = P.COD_PELI)
   AND 0 < (SELECT COUNT(*) FROM ACTUA AC WHERE AC.COD_PELI=P.COD_PELI)
ORDER BY P.TITULO;

-- Consulta 44
SELECT PA.COD_PAIS, PA.NOMBRE, COUNT(A.COD_ACT) 
FROM PAIS PA, ACTOR A
WHERE A.COD_PAIS=PA.COD_PAIS
	AND A.COD_ACT IN (
		SELECT COD_ACT FROM ACTUA AC WHERE AC.COD_PELI IN (
			SELECT COD_PELI FROM PELICULA WHERE ANYO BETWEEN 1960 AND 1969
		)
	)
GROUP BY PA.COD_PAIS, PA.NOMBRE
HAVING 1 <= (
	SELECT COUNT(*) FROM ACTUA AC, PELICULA P 
	WHERE P.ANYO BETWEEN 1960 AND 1969
	AND AC.COD_ACT IN (
		SELECT A2.COD_ACT FROM ACTOR A2 WHERE A2.COD_PAIS=PA.COD_PAIS
		AND P.COD_PELI = AC.COD_PELI
	)
) ORDER BY PA.NOMBRE;

-- Consulta 45
SELECT G.COD_GEN, G.NOMBRE
FROM GENERO G
GROUP BY G.COD_GEN, G.NOMBRE
HAVING (SELECT MAX(NUM) FROM (
	SELECT C.COD_GEN, COUNT(COD_PELI) NUM FROM CLASIFICACION C 
	WHERE C.COD_GEN IN (SELECT COD_GEN FROM CLASIFICACION)
	GROUP BY C.COD_GEN
	)) = (SELECT COUNT(*) FROM CLASIFICACION C WHERE C.COD_GEN = G.COD_GEN);

-- Consulta 46
SELECT L.COD_LIB, L.TITULO, L.AUTOR FROM LIBRO_PELI L
GROUP BY L.COD_LIB, L.TITULO, L.AUTOR
HAVING (
	SELECT MAX(NUM) FROM (
		SELECT COD_LIB, COUNT(COD_LIB) NUM FROM PELICULA
		WHERE COD_LIB IS NOT NULL
		GROUP BY COD_LIB)) 
	= (SELECT COUNT(*) FROM PELICULA P WHERE P.COD_LIB=L.COD_LIB);

-- Consulta 47
SELECT PA.COD_PAIS, PA.NOMBRE FROM PAIS PA
GROUP BY PA.COD_PAIS, PA.NOMBRE
HAVING (
SELECT MAX(MAX_PAIS) FROM (
	-- Tabla que indica el # de actores que han participado en 2 películas por país
	SELECT A.COD_PAIS, COUNT(A.COD_ACT) MAX_PAIS FROM ACTOR A
	WHERE 2 = (SELECT COUNT(*) FROM ACTUA AC WHERE A.COD_ACT=AC.COD_ACT)
	GROUP BY A.COD_PAIS)) 
	= 
	(SELECT COUNT(*) FROM (SELECT A.COD_PAIS, A.COD_ACT  FROM ACTOR A
	WHERE 2 = (SELECT COUNT(*) FROM ACTUA AC WHERE AC.COD_ACT=A.COD_ACT AND A.COD_PAIS=PA.COD_PAIS)
	GROUP BY A.COD_PAIS , A.COD_ACT));

-- Consulta 48
SELECT EXTRACT(YEAR FROM A.FECHA_NAC) AÑO, COUNT(*) CUANTOS
FROM ACTOR A
GROUP BY EXTRACT(YEAR FROM A.FECHA_NAC)
HAVING 3 < (SELECT COUNT(*) FROM ACTOR A2 WHERE EXTRACT(YEAR FROM A.FECHA_NAC) 
			= EXTRACT(YEAR FROM A2.FECHA_NAC)
		);

-- Consulta 49
SELECT P.COD_PELI, P.TITULO FROM PELICULA P
WHERE P.DURACION < 100
GROUP BY P.COD_PELI, P.TITULO
HAVING NOT EXISTS (
 	SELECT * FROM ACTOR A WHERE A.COD_ACT IN (
 		SELECT COD_ACT FROM ACTUA A WHERE A.COD_PELI = P.COD_PELI
 	) AND 1 < ( SELECT COUNT(DISTINCT COD_PAIS) FROM ACTOR ACT WHERE ACT.COD_ACT IN (
 					SELECT COD_ACT FROM ACTUA A WHERE A.COD_PELI = P.COD_PELI) 
 	)
 ) AND P.COD_PELI IN (SELECT COD_PELI FROM ACTUA)
ORDER BY P.COD_PELI;

-- Consulta 50
SELECT P.COD_PAIS, P.NOMBRE, COUNT(A.COD_ACT) CUÁNTOS FROM PAIS P
LEFT JOIN ACTOR A
ON A.COD_PAIS = P.COD_PAIS
GROUP BY P.COD_PAIS, P.NOMBRE
ORDER BY P.NOMBRE;

-- Consulta 51
SELECT L.COD_LIB, L.TITULO, COUNT(P.COD_PELI) CUÁNTAS FROM LIBRO_PELI L
LEFT JOIN PELICULA P
ON L.COD_LIB=P.COD_LIB
WHERE L.ANYO > 1980
GROUP BY L.COD_LIB, L.TITULO;

-- Consulta 52
SELECT P.COD_PAIS, P.NOMBRE, COUNT(A.COD_ACT) CUÁNTOS FROM PAIS P
LEFT JOIN 
(SELECT DISTINCT * FROM ACTOR A2 JOIN (SELECT COD_ACT CA2 FROM ACTUA WHERE PAPEL='Secundario') AC
	ON A2.COD_ACT=AC.CA2) A
ON A.COD_PAIS=P.COD_PAIS 
GROUP BY P.COD_PAIS, P.NOMBRE
ORDER BY P.NOMBRE;

-- Consulta 53
SELECT P.COD_PELI, P.TITULO, COUNT(DISTINCT C.COD_GEN) GEN, COUNT(DISTINCT A.COD_ACT) ACT FROM PELICULA P
LEFT JOIN CLASIFICACION C
ON P.COD_PELI = C.COD_PELI
LEFT JOIN ACTUA A
ON P.COD_PELI = A.COD_PELI
WHERE P.DURACION > 140
GROUP BY P.COD_PELI, P.TITULO
ORDER BY P.TITULO;

-- Consulta 54
SELECT * FROM (
	SELECT ANYO FROM LIBRO_PELI 
	UNION 
	SELECT ANYO FROM PELICULA
) 
WHERE ANYO NOT LIKE '%9%' AND ANYO IS NOT NULL
ORDER BY ANYO ASC;

-- Consulta 55
SELECT G.COD_GEN, G.NOMBRE FROM GENERO G, CLASIFICACION C, PELICULA P
WHERE P.COD_PELI=C.COD_PELI AND C.COD_GEN=G.COD_GEN
AND P.DURACION = (SELECT MAX(DURACION) FROM PELICULA);

-- Consulta 56
SELECT A.COD_ACT, A.NOMBRE, A.FECHA_NAC, COUNT(AC.COD_PELI) CUANTOS_PRINCIP 
FROM ACTOR A
LEFT JOIN ACTUA AC
ON A.COD_ACT=AC.COD_ACT AND AC.PAPEL='Principal'
WHERE A.FECHA_NAC < TO_DATE('01-01-1948', 'dd-MM-yyyy')
GROUP BY  A.COD_ACT, A.NOMBRE, A.FECHA_NAC
HAVING 1 < (SELECT COUNT(*) FROM ACTUA AC2 WHERE AC2.COD_ACT=A.COD_ACT)
ORDER BY A.NOMBRE;

-- Consulta 57
SELECT DISTINCT A.COD_ACT, A.NOMBRE FROM ACTOR A
WHERE NOT EXISTS (
	SELECT * FROM ACTUA AC, PELICULA P
	WHERE AC.COD_ACT=A.COD_ACT AND AC.COD_PELI = P.COD_PELI
	AND P.ANYO < 1994
) AND A.COD_ACT IN (SELECT COD_ACT FROM ACTUA)
ORDER BY A.NOMBRE;


/************************
 * BASE DE DATOS MÚSICA *
 ************************/

-- Consulta 1
SELECT COUNT(*) DISCOS FROM DISCO;

-- Consulta 2
SELECT NOMBRE FROM GRUPO WHERE PAIS <> 'España';

-- Consulta 3
SELECT TITULO FROM CANCION WHERE DURACION > 5;

-- Consulta 4
SELECT DISTINCT FUNCION FROM PERTENECE ORDER BY FUNCION;

-- Consulta 5
SELECT NOMBRE CLUB, NUM TAMAÑO FROM CLUB ORDER BY TAMAÑO;

-- Consulta 6
SELECT NOMBRE, SEDE FROM CLUB WHERE NUM > 500;

-- Consulta 7
SELECT C.NOMBRE, C.SEDE, G.NOMBRE FROM CLUB C, GRUPO G
WHERE C.COD_GRU=G.COD AND G.PAIS='España';

-- Consulta 8
SELECT A.NOMBRE FROM ARTISTA A, PERTENECE P, GRUPO G
WHERE A.DNI = P.DNI AND P.COD = G.COD AND G.PAIS='España' ORDER BY A.NOMBRE;

-- Consulta 9
SELECT DISTINCT D.NOMBRE FROM DISCO D, ESTA E, CANCION C
WHERE D.COD = E.COD AND E.CAN = C.COD AND C.DURACION > 5;

-- Consulta 10
SELECT DISTINCT C.TITULO FROM CANCION C, ESTA E, DISCO D
WHERE C.COD=E.CAN AND E.COD=D.COD AND C.TITULO=D.NOMBRE;

-- Consulta 11
SELECT C.NOMBRE, C.DIR FROM COMPANYIA C, DISCO D
WHERE C.COD=D.COD_COMP AND D.NOMBRE LIKE 'A%';

-- Consulta 12
SELECT A.DNI FROM ARTISTA A
WHERE 1 < (SELECT COUNT(*) FROM PERTENECE P WHERE A.DNI=P.DNI);

-- Consulta 13
SELECT D.NOMBRE FROM DISCO D
WHERE D.COD_GRU = (SELECT COD FROM GRUPO 
	  WHERE FECHA=(SELECT MIN(FECHA) FROM GRUPO)
);

-- Consulta 14
SELECT D.NOMBRE FROM DISCO D
WHERE D.COD_GRU IN (
		SELECT G.COD FROM GRUPO G
	 	WHERE G.COD IN (
	 		SELECT COD_GRU FROM CLUB WHERE NUM > 5000
));

-- Consulta 15
SELECT NOMBRE, NUM FROM CLUB
WHERE NUM = (SELECT MAX(NUM) FROM CLUB);

-- Consulta 16
SELECT TITULO, DURACION FROM CANCION
WHERE DURACION = (SELECT MAX(DURACION) FROM CANCION);

-- Consulta 17
SELECT C.NOMBRE FROM COMPANYIA C
WHERE NOT EXISTS (
	SELECT * FROM DISCO D WHERE D.COD_COMP = C.COD
	AND D.COD_GRU IN (SELECT COD FROM GRUPO WHERE PAIS='España')
);

-- Consulta 18
SELECT C.NOMBRE FROM COMPANYIA C
WHERE NOT EXISTS (
	SELECT * FROM DISCO D WHERE D.COD_COMP=C.COD
	AND D.COD_GRU IN (SELECT COD FROM GRUPO WHERE PAIS<>'España')
) AND C.COD IN (SELECT COD_COMP FROM DISCO);

-- Consulta 19
SELECT C.NOMBRE, C.DIR FROM COMPANYIA C
WHERE NOT EXISTS (
	SELECT * FROM DISCO D
	WHERE D.COD_GRU IN (SELECT COD_GRU FROM DISCO D WHERE D.COD_COMP=C.COD)
	AND D.COD_COMP <> C.COD
) AND C.COD IN (SELECT COD_COMP FROM DISCO) ORDER BY C.NOMBRE;

-- Consulta 20
SELECT G.NOMBRE, SUM(C.NUM) FANS FROM GRUPO G, CLUB C
WHERE C.COD_GRU = G.COD AND G.PAIS = 'España'
GROUP BY G.NOMBRE;

-- Consulta 21
SELECT G.NOMBRE, COUNT(P.COD) FROM GRUPO G, PERTENECE P
WHERE G.COD=P.COD 
GROUP BY G.NOMBRE
HAVING 2 < 
	(SELECT COUNT(*) FROM PERTENECE P2 WHERE P2.COD
	-- Como G.COD no está en el GROUP BY no se puede comparar directamente
	=(SELECT G2.COD FROM GRUPO G2 WHERE G2.NOMBRE=G.NOMBRE)
) ORDER BY G.NOMBRE;

-- Consulta 22
SELECT G.NOMBRE, COUNT(D.COD) DISCOS FROM GRUPO G, DISCO D
WHERE G.COD=D.COD_GRU
GROUP BY G.NOMBRE;

-- Consulta 23
SELECT C.NOMBRE, COUNT(E.CAN) CANCIONES, C.DIR FROM COMPANYIA C
	LEFT JOIN DISCO D ON C.COD=D.COD_COMP
	LEFT JOIN ESTA E  ON E.COD=D.COD
GROUP BY C.NOMBRE, C.DIR
ORDER BY C.NOMBRE;

-- Consulta 24
SELECT A.NOMBRE FROM ARTISTA A
WHERE A.DNI IN (
	SELECT DNI FROM PERTENECE WHERE COD IN (
		SELECT COD FROM GRUPO WHERE PAIS='Inglaterra' AND COD IN (
			SELECT COD_GRU FROM CLUB WHERE NUM > 500
		)
	)
) ORDER BY A.NOMBRE;

-- Consulta 25
SELECT DISTINCT C.TITULO FROM CANCION C
	JOIN ESTA E ON C.COD=E.CAN
	JOIN DISCO D ON D.COD=E.COD
WHERE D.COD_GRU = (SELECT COD FROM GRUPO WHERE NOMBRE = 'U2')
ORDER BY C.TITULO;

-- Consulta 26
SELECT A.NOMBRE VOZ, A2.NOMBRE GUITARRA FROM ARTISTA A, ARTISTA A2
WHERE A.DNI IN (SELECT DNI FROM PERTENECE WHERE FUNCION='voz')
  AND A2.DNI IN (SELECT DNI FROM PERTENECE WHERE FUNCION='guitarra')
  AND (SELECT COD FROM PERTENECE P WHERE P.DNI=A.DNI) 
  		=
  	  (SELECT COD FROM PERTENECE P WHERE P.DNI=A2.DNI)
  AND (SELECT COD FROM PERTENECE P WHERE P.DNI=A.DNI)
  		IN 
  	  (SELECT COD FROM GRUPO WHERE PAIS='España');
  	
-- Consulta 27
SELECT A.NOMBRE FROM ARTISTA A WHERE 1<(SELECT COUNT(*) FROM PERTENECE P WHERE P.DNI = A.DNI);

--Consulta 28
SELECT C.TITULO FROM CANCION C
WHERE C.DURACION = (SELECT MAX(DURACION) FROM CANCION)
AND 1 = (SELECT COUNT(*) FROM CANCION WHERE DURACION=(SELECT MAX(DURACION) FROM CANCION));

-- Consulta 29
SELECT C.NOMBRE, C.NUM FROM CLUB C
WHERE C.NUM = (SELECT NUM FROM 
	(SELECT ROW_NUMBER() OVER (ORDER BY NUM DESC) AS ROW_NUM, NUM FROM CLUB) 
WHERE ROW_NUM = 10);

-- Consulta 30
SELECT DISTINCT A.NOMBRE FROM ARTISTA A, PERTENECE P
WHERE A.DNI=P.DNI AND P.FUNCION='bajo'
AND 2 < (SELECT COUNT(*) FROM PERTENECE P2 WHERE P2.COD=P.COD)
AND 1 = (SELECT COUNT(*) FROM PERTENECE P3 WHERE P3.DNI=A.DNI AND P3.FUNCION='bajo');

-- Consulta 31
SELECT * FROM (
	SELECT C.NOMBRE, COUNT(E.COD) CANCIONES FROM COMPANYIA C
		LEFT JOIN DISCO D ON C.COD=D.COD_COMP
		LEFT JOIN ESTA E ON D.COD=E.COD
	GROUP BY C.NOMBRE)
WHERE CANCIONES = (
	SELECT MAX(CANCIONES) FROM (
		SELECT C.NOMBRE, COUNT(E.COD) CANCIONES FROM COMPANYIA C
		LEFT JOIN DISCO D ON C.COD=D.COD_COMP
		LEFT JOIN ESTA E ON D.COD=E.COD
	GROUP BY C.NOMBRE
	)
);
  	 
/****************************
 * BASE DE DATOS BIBLIOTECA *
 ****************************/

-- Consulta 1
SELECT NOMBRE FROM AUTOR WHERE NACIONALIDAD='Argentina' ORDER BY NOMBRE;

-- Consulta 2
SELECT TITULO FROM OBRA WHERE TITULO LIKE '%mundo%';

-- Consulta 3
SELECT ID_LIB, NUM_OBRAS FROM LIBRO WHERE AÑO < 1990 AND NUM_OBRAS > 1;

-- Consulta 4
SELECT COUNT(*) LIB_AÑO FROM LIBRO WHERE AÑO IS NOT NULL;

-- Consulta 5
SELECT COUNT(*) MÁS_1_OB FROM LIBRO WHERE NUM_OBRAS > 1;

-- Consulta 6
SELECT ID_LIB FROM LIBRO WHERE AÑO=1997 AND TITULO IS NULL;

-- Consulta 7
SELECT TITULO FROM LIBRO WHERE TITULO IS NOT NULL ORDER BY TITULO DESC;

-- Consulta 8
SELECT SUM(NUM_OBRAS) OBRAS FROM LIBRO WHERE AÑO BETWEEN 1990 AND 1999;

-- Consulta 9
SELECT COUNT(DISTINCT A.NOMBRE) AUTORES FROM AUTOR A, OBRA O, ESCRIBIR E
WHERE A.AUTOR_ID =E.AUTOR_ID AND E.COD_OB=O.COD_OB AND O.TITULO LIKE '%ciudad%';

-- Consulta 10



/**************************
 * BASE DE DATOS CICLISMO *
 **************************/

/******************************
 * BASE DE DATOS DEPARTAMENTO *
 ******************************/
