#!/bin/bash
# arguments
echo El numero de argumentos es: $#
echo La orden completa tecleada es: $0 $@
echo La orden tecleada es: $0
echo El Primer argumento es: $1
echo El Segundo argumento es: $2
echo El tercer argumento es: $3
